# -*- coding: utf-8 -*-
"""preprocesamiento_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQlCcpYYnVm8a9Hb0dD21PQrQcsFK8fd
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


# --------------------------
# CARGA DE DATOS
# --------------------------

def cargar_datos(ruta): #FUNCION ESPERA UN STRING Y RETORNA UN PD.DATAFRAME
#Parámetros: -ruta: ruta al archivo CSV (ej: "retail_store_sales.csv")
#            -Retorna: DataFrame con los datos originales
    raw_df = pd.read_csv(ruta)
    return raw_df.copy()

# ----------------------------------------------------------------
# TRANSFORMACIONES DEL DATASET
# ----------------------------------------------------------------

# CONVERSION DE FECHAS
#convierte columna Transaction date a un timestamp, recibe un df y retorna un df con nueva columna en timestamp
def convertir_fechas(df):
    df = df.copy()
    df['Timestamp'] = pd.to_datetime(df['Transaction Date']).astype('int64') // 10**9
    return df


# LIMPIEZA DE NULOS
def eliminar_irrecuperables(df):
     #elimina las filas donde 'Quantity' y 'Total Spent' son nulos al mismo tiempo,
     #ya que en ese caso no es posible recuperar 'Price Per Unit'.
    df = df.copy()
    filtro = df.loc[df['Quantity'].isnull() & df['Total Spent'].isnull()]
    df.drop(filtro.index, axis=0, inplace=True)
    return df

#Recuperacion de precio unitario nulo
def recuperar_precio_unitario(df):
#Recuperamos valores nulos de 'Price Per Unit' con la formula:  Price Per Unit = Total Spent / Quantity
    df = df.copy()
    df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])
    return df

#Recuperacion de items apartir de Catergory y Price Per unit
def recuperar_items(df: pd.DataFrame) -> pd.DataFrame:
    #OJO  Solo funciona si dentro de cada categoria no existen dos items con el  mismo precio unitario
    df = df.copy()

    # Construimos el diccionario solo con filas que tienen Item conocido
    not_null_items = df.loc[df['Item'].notna()].copy()
    item_dict = not_null_items.set_index(['Category', 'Price Per Unit'])['Item'].to_dict()

    # Identificamos las filas con Item nulo
    null_item_mask = df[df['Item'].isna()]
    categorias = null_item_mask['Category'].tolist()
    precios = null_item_mask['Price Per Unit'].tolist()

    # Buscamos cada Item en el diccionario
    nombres_recuperados = [
        item_dict.get((categorias[i], precios[i]))
        for i in range(len(categorias))
    ]

    df.loc[null_item_mask.index, 'Item'] = nombres_recuperados
    return df

#eliminacion de cualquier dato con descuento nulo (CRITERIO PENDIENTE DE REVISION)
def eliminar_nulos_descuento(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    filtro = df.loc[df['Discount Applied'].isnull()]
    df.drop(filtro.index, axis=0, inplace=True)
    return df


# ------------------------------------------------------
# TRANSFORMACIONES
#---------------------------------------------------
# NOTA: Esta transformacion usa LabelEncoder para variables categoricas.
# LabelEncoder asigna numeros secuenciales (0, 1, 2...) lo que implica un orden
# artificial entre categorias (ej: Location 2 > Location 1 para el modelo).
# Se conserva como alternativa comparativa. Para modelado real, usar pipeline_clasificacion
# o pipeline_regresion que usan OneHotEncoder.
def transformacion_manual(df):
    df_manual = df.copy()
    le = LabelEncoder()
    mm_scaler = MinMaxScaler()

    # Encoding de variables categoricas
    df_manual['Categoria']          = le.fit_transform(df_manual['Category'])
    df_manual['Item']               = le.fit_transform(df_manual['Item'])
    df_manual['Metodo_de_pago']     = le.fit_transform(df_manual['Payment Method'])
    df_manual['Locacion']           = le.fit_transform(df_manual['Location'])
    df_manual['Descuento_Aplicado'] = le.fit_transform(df_manual['Discount Applied']) # True o False de descuento

    # Escalado de variables numericas
    df_manual['Precio_Unitario_Norm'] = mm_scaler.fit_transform(df_manual[['Price Per Unit']])
    df_manual['Cantidad_Norm']        = mm_scaler.fit_transform(df_manual[['Quantity']])
    df_manual['Total_Norm']           = mm_scaler.fit_transform(df_manual[['Total Spent']])
    df_manual['Timestamp_Norm']       = mm_scaler.fit_transform(df_manual[['Timestamp']])

    return df_manual

def pipeline_clasificacion(df):
    # Target: Discount Applied (True/False --> 1/0)
    # Features: todo excepto el target, Transaction ID, Customer ID y Transaction Date
    df_auto = df.copy()

    X = df_auto[['Category', 'Item', 'Payment Method', 'Location', 'Price Per Unit', 'Quantity', 'Total Spent', 'Timestamp']]
    y = (df_auto['Discount Applied'] == True).astype(int)

    pipeline = ColumnTransformer(transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'),
         ['Category', 'Item', 'Payment Method', 'Location']),
        ('num', StandardScaler(),
         ['Price Per Unit', 'Quantity', 'Total Spent', 'Timestamp'])
    ])

    X_transf = pipeline.fit_transform(X)
    return X_transf, y


def pipeline_regresion(df):
    # Target: Total Spent (valor continuo)
    # Features: todo excepto el target, Transaction ID, Customer ID y Transaction Date
    # Discount Applied se convierte a 0/1 antes de escalar ya que es booleano
    df_auto = df.copy()

    X = df_auto[['Category', 'Item', 'Payment Method', 'Location','Discount Applied', 'Price Per Unit', 'Quantity', 'Timestamp']]
    y = df_auto['Total Spent']

    X = X.copy()
    X['Discount Applied'] = (X['Discount Applied'] == True).astype(int)

    pipeline = ColumnTransformer(transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'),
         ['Category', 'Item', 'Payment Method', 'Location']),
        ('num', StandardScaler(),
         ['Discount Applied', 'Price Per Unit', 'Quantity', 'Timestamp'])
    ])

    X_transf = pipeline.fit_transform(X)
    return X_transf, y



# ------------------------------------------------
# FUNCION CONTROLADOR
# -----------------------------------------------
#(aqui ejecutamos todas las funciones anteriores en orden como si de un controlador se tratara, otros archivos solo ejecutan esto para ejecutar el resto)

def preprocesar(ruta: str):
    df = cargar_datos(ruta)
    df = convertir_fechas(df)
    df = eliminar_irrecuperables(df)
    df = recuperar_precio_unitario(df)
    df = recuperar_items(df)
    df = eliminar_nulos_descuento(df)
    return df